### ISSUE TITLE
 JFusion plugin wizard not working

### ISSUE THREAD

**Issue by pronkster** [fanno/org.jfusion.phpbb31#1]
I have installed the latest plugin with phpbb 3.1 and so far the following does not work for me:

The Jfusion configure plugin wizard is not working: 

WARNING: phpbb3: Could not connect to Database, please check your configuration Unable to load Database Driver: phpbbdbdrivermysqli - All settings are exactly the same as the working version and confirmed correct.

**Comment by fanno** [comment]
hmm, https://github.com/fanno/org.jfusion.phpbb31/blob/master/admin.php#L79 should haved fixed that.
It should extract driver from dbms .. eg \phpbb\db\driver\mysqli

perhaps i changed something after the fact and don't remember.

-Thanks

**Comment by pronkster** [comment]
I'll have another try again soon, I may have used the wrong files thinking about it now.

**Comment by pronkster** [comment]
The wizard is working with the latest plugin files. Thanks :+1:
