### ISSUE TITLE
Can't install in Joomla

### ISSUE THREAD

**Issue by ccgr** [fanno/org.jfusion.phpbb31#5]
Message
Error installing COM_INSTALLER_TYPE_TYPE_JFUSION

**Comment by fanno** [comment]
Where are you preforming the install??

**Comment by ccgr** [comment]
I tried to install this version via joomla 3's extension manager

**Comment by fanno** [comment]
thats your problem, it is not a joomla extention it is a jfusion extention/addon you need to install it via jfusion cpanel

**Comment by ccgr** [comment]
much better, thanks, there's an issue with alpha user points but they may have existed before phpBB 3.1  

sysplgaup_newregistered User Plugin Error

**Comment by fanno** [comment]
hmm where are you getting this ?

**Comment by ccgr** [comment]
In the login checker, sorry

**Comment by fanno** [comment]
hmmm i don't have any idea why this error would e related to phpbb 3.1 (if it is)

is login not working ? i assume ? or ? what if that plugin is disabled ?

-Thanks

**Comment by ccgr** [comment]
The login still works

**Comment by fanno** [comment]
hmm ok,they i dont know =/ about that.

-Sorry

p.s.
I am soon "ready" with a auth mod (atleast ready for testing)
