### ISSUE TITLE
When im trying to add a file in a topic (like an image) I have php error...

### ISSUE THREAD

**Issue by electro143** [fanno/org.jfusion.phpbb31#7]
It give me that error (in french)

Erreur

Erreur HTTP.

The option for adding file is activated in phpbb and I have set the file size for bigger files but it is not working...

**Comment by electro143** [comment]
Now when im trying to attach an image nothink happen :-/ ...May it be something with the frameless that cause this issue?

**Comment by electro143** [comment]
I think the error may come because ''option'' ''attachment'' and ''pool'' is all on the same tab...
![untitled-2](https://cloud.githubusercontent.com/assets/9616210/5119767/54907c22-7044-11e4-8bce-92b2c5bebd19.gif)

**Comment by fanno** [comment]
> The option for adding file is activated in phpbb and I have set the file size for bigger files but it is not working...

do small files work ?

**Comment by electro143** [comment]
Ive desactivated jfusion for now and im using my forum as standalone for now...Ill wait for it to be more finished with phpbb3.1.Thank for your help!

Before Ive desactivated it nothing was working on file upload...I was clicking a file to upload it and then nothing happened...Ive tryied it many times with different file size and format...

**Comment by fanno** [comment]
I cant recreate it at this point in time, may have been fixed by another url error. i solved.

closing it create a new if same issue is still there.

-Thanks
