### ISSUE TITLE
Can't delete ''private'' messages

### ISSUE THREAD

**Issue by electro143** [fanno/org.jfusion.phpbb31#8]
I've sent private message between 2 user...Seem to work great but i can't delete my private messages!

**Comment by fanno** [comment]
I assume it is frameless correct ? if so i wont work on this unless i solve the major integration problem =/

**Comment by electro143** [comment]
What do you mean by correct?Everything seem correct except that private message bug and the bbcode and attachment problem...Otherwise everything work great...

**Comment by fanno** [comment]
i just wanted to verify that this issue was also in frameless.. =)

**Comment by fanno** [comment]
This should be fixed by latest update. frameless can possibly be done with curl frameless for "app.php" so i will keep trying as long as that is a hope.

**Comment by electro143** [comment]
Ive desactivated jfusion for now and im using my forum as standalone for now...Ill wait for it to be more finished with phpbb3.1.Thank for your help!
