### ISSUE TITLE
bbcode not working

### ISSUE THREAD

**Issue by electro143** [fanno/org.jfusion.phpbb31#9]
bbcode seem to not working...Ive tried add an image with the bbcode ''img'' and it only show the text ''image''

**Comment by fanno** [comment]
Any bbcode? or image?

**Comment by electro143** [comment]
seem to be only image right now...

**Comment by electro143** [comment]
When I check the word ''image'' shown with firebug it give me that code :

<img class="postimage" alt="Image" src="http://quebeccoquin.com/forum/http://www.imagesdoc.com/var/bayard/storage/images/smk/images-doc/images/images-doc-plus/que-vois-tu/photo-mystere-1-image-3/24513080-1-fre-FR/Photo-mystere-1-Image-3.jpg">

But it also saying ''impossible de cahr l'url indiqué''

**Comment by fanno** [comment]
I can't looks markdown breaks what you tried to post.

I also don't know what "impossible de cahr l'url indiqué" means

**Comment by electro143** [comment]
Here what i saw...And ''impossible de charger l'url indiqué'' mean ''cant show the indicated url'' or something like that (im not that good in english) ...It was an image on a url ive taked on another on another website...

![untitled-1](https://cloud.githubusercontent.com/assets/9616210/5128729/f0a99a4c-70aa-11e4-9c3a-8370ca7a6f5b.gif)

**Comment by electro143** [comment]
Additional note : the word ''images'' in my post is not ''clickable''

**Comment by electro143** [comment]
I think I found the solution...The forum want to get the url of the image with the url of my website before it...After I remove it with firebug it show image!Don't know what to modify for a permanent fix thougt :-/

![imageforum1](https://cloud.githubusercontent.com/assets/9616210/5144144/c863f864-7165-11e4-8ffe-1a16f3443eac.jpg)
![imageforum2](https://cloud.githubusercontent.com/assets/9616210/5144151/d18cd64a-7165-11e4-9ee5-395193ca44a7.jpg)

**Comment by fanno** [comment]
closing this one also as i believe it is already fixed.
